### ISSUE TITLE
5(18).ページを完成させる

### ISSUE THREAD

**Issue by KEISUKE0293** [KEISUKE0293/keisuke0293-frontend-basic-last-assignment#21]
[FrontendBasicのWebページ](https://basic-frontend.4nonome.com/lastAssignment/page/)の指示通りにコマンドを入力したら以下のようなエラーメッセージが出ました。
この前案件の環境構築の際にNode.jsのバージョンをv16.13.2にしたのですがそれが関係しているのでしょうか？
色々調べたのですが自分で解決しようとして更に状況悪化するのが怖いのでアドバイスをいただきたいです。

$ yarn build-sass        
yarn run v1.22.11
$ gulp
Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.14.1
    at module.exports (C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\binding.js:13:13)
    at Object.<anonymous> (C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\index.js:14:35)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\gulp-sass\index.js:166:21)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> yarn run v1.22.11
yarn run v1.22.11
error Command "v1.22.11" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> $ gulp
$: The term '$' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (93)
Error:: The term 'Error:' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> For more information on which environments are supported please see:
ParserError: 
Line |
   1 |  For more information on which environments are supported please see:
     |     ~
     | Missing opening '(' after keyword 'for'.

PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> https://github.com/sass/node-sass/releases/tag/v4.14.1
https://github.com/sass/node-sass/releases/tag/v4.14.1: The term 'https://github.com/sass/node-sass/releases/tag/v4.14.1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at module.exports (C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\binding.js:13:13)
C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\binding.js:13:13: The term 'C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\binding.js:13:13' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Object.<anonymous> (C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\index.js:14:35)
C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\index.js:14:35: The term 'C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\node-sass\lib\index.js:14:35' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
node:internal/modules/cjs/loader:1101:14: The term 'node:internal/modules/cjs/loader:1101:14' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)      
node:internal/modules/cjs/loader:1153:10: The term 'node:internal/modules/cjs/loader:1153:10' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Module.load (node:internal/modules/cjs/loader:981:32)
node:internal/modules/cjs/loader:981:32: The term 'node:internal/modules/cjs/loader:981:32' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Function.Module._load (node:internal/modules/cjs/loader:822:12)
node:internal/modules/cjs/loader:822:12: The term 'node:internal/modules/cjs/loader:822:12' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Module.require (node:internal/modules/cjs/loader:1005:19)
node:internal/modules/cjs/loader:1005:19: The term 'node:internal/modules/cjs/loader:1005:19' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at require (node:internal/modules/cjs/helpers:102:18)
node:internal/modules/cjs/helpers:102:18: The term 'node:internal/modules/cjs/helpers:102:18' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Object.<anonymous> (C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\gulp-sass\index.js:166:21)
C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\gulp-sass\index.js:166:21: The term 'C:\Users\k27do\keisuke0293-frontend-basic-last-assignment\node_modules\gulp-sass\index.js:166:21' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment>     at Module._compile (node:internal/modules/cjs/loader:1101:14)
node:internal/modules/cjs/loader:1101:14: The term 'node:internal/modules/cjs/loader:1101:14' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> error Command failed with exit code 1.
Get-Error: A positional parameter cannot be found that accepts argument 'failed'.
PS C:\Users\k27do\keisuke0293-frontend-basic-last-assignment> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kodai01** [comment]
macだとnodeのバージョン12だと動きますが16に上げたら動かないようです。

nodebrewを使ってnodeのバージョンを管理してたら変えるのは簡単ですのでバージョンを落としたものをインストールしてそれを使うように指示してください。

もし使ってないようだったら、上書きすると今度は案件の方で動かなくなる可能性があるので、上で説明したようにnodebrewをインストールした上でPATHを通した上で上記操作を行うのが安全だと思います。

---

＊自分はmacなのでこれで直りますが、windowsの場合だと必ずしもこれで直るかどうかは不明です。

**Comment by MoAI522** [comment]
試したところ、WindowsでもNode.jsのバージョン違いにより動かないようです。
以前、[テンプレートリポジトリ](https://github.com/shinonome-inc/frontend-basic-last-assignment-2021)の方をバージョン16に対応したので、そちらのpackage.jsonとyarn.lockを持ってきて、再度yarn installから実行していただけますか？
kodaiさんの言うバージョン下げる対応でも可能ですが、案件で使うのであればこちらの方法を試していただけると幸いです。
